Finish Windows Runtime

diff --git a/Makefile.all b/Makefile.all
--- a/Makefile.all
+++ b/Makefile.all
@@ -9,8 +9,13 @@ RUNTIME_OBJ = $(addprefix build/, $(RUNTIME_SRC:.c=.o))
 RUNTIME_OBJ += $(addprefix build/, $(ASSEMBLY_SRC:.S=.o))
 RUNTIME_OBJ +=  $(addprefix build/, $(RUNTIME_LISP_SRC:.scm=.o))
 
+DEP += $(addprefix build/x86_64-w64-mingw32/, $(RUNTIME_SRC:.c=.d) $(RUNTIME_LISP_SRC:.scm=.d))
+WINDOWS_RUNTIME_OBJ = $(addprefix build/x86_64-w64-mingw32/, $(RUNTIME_SRC:.c=.o))
+WINDOWS_RUNTIME_OBJ += $(addprefix build/x86_64-w64-mingw32/, $(WINDOWS_ASSEMBLY_SRC:.S=.o))
+WINDOWS_RUNTIME_OBJ +=  $(addprefix build/x86_64-w64-mingw32/, $(RUNTIME_LISP_SRC:.scm=.o))
+
 BOOT = $(addprefix bin/bootstrap/src/, $(SRC:.scm=.c))
-BOOT += $(addprefix bin/bootstrap/runtime/, $(ASSEMBLY_SRC) $(RUNTIME_SRC) $(RUNTIME_LISP_SRC:.scm=.c))
+BOOT += $(addprefix bin/bootstrap/runtime/, $(ASSEMBLY_SRC) $(WINDOWS_ASSEMBLY_SRC) $(RUNTIME_SRC) $(RUNTIME_LISP_SRC:.scm=.c))
 
 STRAP = $(addprefix bootstrap/src/, $(SRC:.scm=.c))
 
@@ -19,20 +24,23 @@ VSC = vsc.$(MAJOR)
 
 include config.mk
 
-.PHONY : deps install compiler runtime tests install_compiler lay_egg testffi
+.PHONY : deps install compiler runtime windows_runtime tests install_compiler lay_egg testffi
 compiler : bin/vsc
 runtime : lib/libvscheme.so
+windows_runtime : lib/x86_64-w64-mingw32/vscheme.dll
 
 # the include copy doesn't have an -u on it because
 # include files aren't build. Can add the -u if we
 # copy the files to the bin directory
-install : compiler runtime
-	mkdir -p ~/.local/include/vscheme/
-	mkdir -p ~/.local/lib/
+install : compiler runtime windows_runtime
 	cp -u lib/libvscheme.so $(INSTALL_DIR)/lib/$(VSCHEME)
 	ldconfig
 	cp -r include/* $(INSTALL_DIR)/include/.
 	cp -u bin/vsc $(INSTALL_DIR)/bin/$(VSC)
+	mkdir -p $(INSTALL_DIR)/x86_64-w64-mingw32/include
+	mkdir -p $(INSTALL_DIR)/x86_64-w64-mingw32/lib
+	ln -sfn $(INSTALL_DIR)/include/vscheme $(INSTALL_DIR)/x86_64-w64-mingw32/include/vscheme
+	cp -u lib/x86_64-w64-mingw32/vscheme.dll $(INSTALL_DIR)/x86_64-w64-mingw32/lib/
 
 tests : compiler runtime
 	@for test in $(addprefix test/, $(TEST_SRC)) ; do \
@@ -44,6 +52,22 @@ tests : compiler runtime
 	  fi ; \
     EXE=`realpath a.out` ; \
 		if ! (cd `dirname $$test` ; LD_LIBRARY_PATH=$$OVERRIDE:$$LD_LIBRARY_PATH $$EXE) ; then \
+			echo "FAILURE: $$test"; \
+			exit 1; \
+		fi \
+	done
+
+tests_windows : compiler windows_runtime
+	@for test in $(addprefix test/, $(TEST_SRC)) ; do \
+		echo "bin/vsc $$test && wine ./a.exe" ; \
+    OVERRIDE=`realpath lib/` ; \
+		if ! (LD_LIBRARY_PATH=$$OVERRIDE:$$LD_LIBRARY_PATH bin/vsc $$test -Wc,-Iinclude -Iinclude --platform=windows) ; then \
+			echo "COMPILE FAILURE: $$test"; \
+			exit 1; \
+	  fi ; \
+		ln -sf `realpath lib/x86_64-w64-mingw32/vscheme.dll` `dirname $$test`/; \
+    EXE=`realpath a.exe` ; \
+		if ! (cd `dirname $$test` ; wine $$EXE) ; then \
 			echo "FAILURE: $$test"; \
 			exit 1; \
 		fi \
@@ -73,6 +97,8 @@ deps : $(DEP)
 
 build/%.d : runtime/%.c
 	gcc $< -MG -MM -MF $@ -MT $@ -MT $(@:.d=.o) $(CFLAGS) $(IFLAGS)
+build/x86_64-w64-mingw32/%.d : runtime/%.c
+	gcc $< -MG -MM -MF $@ -MT $@ -MT $(@:.d=.o) $(CFLAGS) $(IFLAGS)
 build/%.d : runtime/%.S
 	echo '$(@,.d=.o) $@: $<' > $@
 build/%.d : src/%.scm
@@ -85,13 +111,23 @@ build/%.d : runtime/%.scm
 	@mkdir -p `dirname build/headers/$*.scmh`
 	vsc --makefile $< -o $@ --maketarget $(@:.d=.o)
 	vsc --makefile $< -o build/headers/$*.d --maketarget $(@:.d=.scmh)
+build/x86_64-w64-mingw32/%.d : runtime/%.scm
+	@mkdir -p `dirname $@`
+	@mkdir -p `dirname build/headers/$*.scmh`
+	vsc --makefile $< -o $@ --maketarget $(@:.d=.o)
+	vsc --makefile $< -o build/headers/$*.d --maketarget $(@:.d=.scmh)
 
 -include $(DEP)
 
 bin/vsc : $(OBJ)
 	vsc -o $@ $^ $(SCMFLAGS)
+
 lib/libvscheme.so : $(RUNTIME_OBJ)
 	gcc -o $@ $^ $(LIBS) $(CFLAGS) -shared
+
+lib/x86_64-w64-mingw32/vscheme.dll : $(WINDOWS_RUNTIME_OBJ)
+	@mkdir -p `dirname $@`
+	/usr/bin/x86_64-w64-mingw32-gcc -o $@ $^ $(CFLAGS) -shared -Wl,--export-all-symbols -Wl,--stack,8388608
 
 build/%.scmh : src/%.scm
 	@mkdir -p `dirname $@`
@@ -116,11 +152,21 @@ build/%.o : runtime/%.scm
 	@mkdir -p `dirname $@`
 	vsc -c $< -o $@ $(SCMFLAGS) --shared -Iinclude
 
-build/%.o : runtime/%.c build/%.d 
+build/x86_64-w64-mingw32/%.o : runtime/%.scm
+	@mkdir -p `dirname $@`
+	vsc -c $< -o $@ $(SCMFLAGS) --shared -Iinclude --platform=windows
+
+build/%.o : runtime/%.c
 	gcc -c $< -o $@ $(CFLAGS) $(IFLAGS)
+
+build/x86_64-w64-mingw32/%.o : runtime/%.c
+	/usr/bin/x86_64-w64-mingw32-gcc -c $< -o $@ $(CFLAGS) $(IFLAGS)
 
 build/%.o : runtime/%.S 
 	gcc -c $< -o $@ $(CFLAGS) $(IFLAGS)
+
+build/x86_64-w64-mingw32/%.o : runtime/%.S 
+	/usr/bin/x86_64-w64-mingw32-gcc -c $< -o $@ $(CFLAGS) $(IFLAGS)
 
 build/%.o : src/%.scm
 	@mkdir -p `dirname $@`
