preflight build

diff --git a/Makefile.all b/Makefile.all
--- a/Makefile.all
+++ b/Makefile.all
@@ -17,6 +17,11 @@ CC = gcc
 #PATCH := LD_PRELOAD=~/vscheme/libpatch.so
 PATCH :=
 
+# VSC_DEP, when set to the path of the compiler, makes every
+# vsc-generated file depend on the compiler binary itself
+VSC ?= vsc
+VSC_DEP ?=
+
 ifeq ($(ENABLE_WINDOWS),y)
 windows_runtime windows_interpreter : CC = /usr/bin/x86_64-w64-mingw32-gcc
 windows_runtime windows_interpreter : CFLAGS += -Wa,--no-warn -lshlwapi
@@ -112,46 +117,51 @@ ifeq ($(ENABLE_WASM),y)
 	install -m644 vendor/lib/wasm/* $(EMSCRIPTEN_INSTALL_DIR)/lib/wasm32-emscripten/
 endif
 
-tests_linux : compiler runtime
-	@for test in $(addprefix test/, $(TEST_SRC)) ; do \
-    ( EXE=`mktemp` ; \
-		echo "bin/vsc $$test && ./a.out" ; \
-    OVERRIDE=`realpath lib/` ; \
-		if ! ($(PATCH) LD_LIBRARY_PATH=$$OVERRIDE:$$LD_LIBRARY_PATH bin/vsc -o$$EXE $$test -O2 -Wc,-Llib -Wc,-Iinclude -Wc,-lm -Iinclude ) ; then \
-			echo "COMPILE FAILURE: $$test"; \
-      \rm -f $$EXE ; \
-			exit 1; \
-	  fi ; \
-		if ! (cd `dirname $$test` ; $(PATCH) LD_LIBRARY_PATH=$$OVERRIDE:$$LD_LIBRARY_PATH $$EXE) ; then \
-			echo "FAILURE: $$test"; \
-      \rm -f $$EXE ; \
-			exit 1; \
-		fi ; \
-    \rm -f $$EXE ; ) & \
-	done ; \
-	wait
+TESTRUN_LINUX := $(addprefix testrun_linux/, $(TEST_SRC))
+
+tests_linux : $(TESTRUN_LINUX)
+
+testrun_linux/% : compiler runtime
+	@EXE=`mktemp` ; \
+	echo "bin/vsc test/$* && ./a.out" ; \
+	OVERRIDE=`realpath lib/` ; \
+	if ! ($(PATCH) LD_LIBRARY_PATH=$$OVERRIDE:$$LD_LIBRARY_PATH bin/vsc -o$$EXE test/$* -O2 -Wc,-Llib -Wc,-Iinclude -Wc,-lm -Iinclude ) ; then \
+		echo "COMPILE FAILURE: test/$*"; \
+		\rm -f $$EXE ; \
+		exit 1; \
+	fi ; \
+	if ! (cd test/`dirname $*` ; $(PATCH) LD_LIBRARY_PATH=$$OVERRIDE:$$LD_LIBRARY_PATH $$EXE) ; then \
+		echo "FAILURE: test/$*"; \
+		\rm -f $$EXE ; \
+		exit 1; \
+	fi ; \
+	\rm -f $$EXE
+
+TESTRUN_WINDOWS := $(addprefix testrun_windows/, $(TEST_SRC))
 
 ifeq ($(ENABLE_WINDOWS),y)
-tests_windows : compiler runtime windows_runtime
-	@for test in $(addprefix test/, $(TEST_SRC)) ; do \
-    ( EXE=`mktemp` ; \
-		echo "bin/vsc $$test && wine ./a.exe" ; \
-    OVERRIDE="`realpath lib/`:`realpath vendor/lib/`" ; \
-		if ! (LD_LIBRARY_PATH=$$OVERRIDE:$$LD_LIBRARY_PATH bin/vsc -o$$EXE $$test -Wc,-Llib/x86_64-w64-mingw32 -Wc,-Lvendor/lib/x86_64-w64-mingw32  -Wc,-Iinclude -Iinclude --platform=windows) ; then \
-			echo "COMPILE FAILURE: $$test"; \
-      \rm -f $$EXE ; \
-			exit 1; \
-	  fi ; \
-		ln -sf `realpath lib/x86_64-w64-mingw32/vscheme.dll` `dirname $$test`/; \
-		ln -sf `realpath vendor/lib/x86_64-w64-mingw32/dfile.dll` `dirname $$test`/; \
-		if ! (cd `dirname $$test` ; wine $$EXE) ; then \
-			echo "FAILURE: $$test"; \
-      \rm -f $$EXE ; \
-			exit 1; \
-		fi ; \
-    \rm -f $$EXE ; ) & \
-	done ; \
-	wait
+tests_windows : $(TESTRUN_WINDOWS)
+
+testrun_windows/% : compiler runtime windows_runtime
+	@EXE=`mktemp` ; \
+	echo "bin/vsc test/$* && wine ./a.exe" ; \
+	OVERRIDE="`realpath lib/`:`realpath vendor/lib/`" ; \
+	if ! (LD_LIBRARY_PATH=$$OVERRIDE:$$LD_LIBRARY_PATH bin/vsc -o$$EXE test/$* -Wc,-Llib/x86_64-w64-mingw32 -Wc,-Lvendor/lib/x86_64-w64-mingw32  -Wc,-Iinclude -Iinclude --platform=windows) ; then \
+		echo "COMPILE FAILURE: test/$*"; \
+		\rm -f $$EXE ; \
+		exit 1; \
+	fi ; \
+	ln -sf `realpath lib/x86_64-w64-mingw32/vscheme.dll` test/`dirname $*`/; \
+	ln -sf `realpath vendor/lib/x86_64-w64-mingw32/dfile.dll` test/`dirname $*`/; \
+	if ! (cd test/`dirname $*` ; wine $$EXE) ; then \
+		echo "FAILURE: test/$*"; \
+		\rm -f $$EXE ; \
+		exit 1; \
+	fi ; \
+	\rm -f $$EXE
+else
+testrun_windows/% :
+	@echo "Windows backend was disabled by ./configure (x86_64-w64-mingw32-gcc); re-run ./configure to enable" ; exit 1
 endif
 
 lay_egg : $(BOOT)
@@ -198,6 +208,9 @@ build/x86_64-w64-mingw32/% : runtime/%
 build/x86_64-w64-mingw32/% : src/%
 	@mkdir -p $(dir $@)
 	ln -sfr $< $@
+build/x86_64-w64-mingw32/% : config/%
+	@mkdir -p $(dir $@)
+	ln -sfr $< $@
 build/wasm/% : runtime/%
 	@mkdir -p $(dir $@)
 	ln -sfr $< $@
@@ -208,17 +221,17 @@ build/% : config/%
 build/%.d : build/%.c
 	gcc $< -MG -MM -MF $@ -MT $@ -MT $(@:.d=.o) $(CFLAGS) $(IFLAGS) -Isrc -Iruntime
 
-build/%.d : build/%.scm
+build/%.d : build/%.scm $(VSC_DEP)
 	@mkdir -p `dirname build/headers/$*.scmh`
-	vsc --makefile $< -o $@ --maketarget $(@:.d=.o)
-	vsc --makefile $< -o build/headers/$*.d --maketarget $(@:.d=.scmh)
+	$(VSC) --makefile $< -o $@ --maketarget $(@:.d=.o)
+	$(VSC) --makefile $< -o build/headers/$*.d --maketarget $(@:.d=.scmh)
 
 -include $(DEP)
 
 bin/vsc : $(OBJ) $(COMPILE_OBJ)
-	vsc -o $@ $^ $(SCMFLAGS) -Wc,-Llib
+	$(VSC) -o $@ $^ $(SCMFLAGS) -Wc,-Llib -Wc,-Lvendor/lib
 bin/vanity : $(OBJ) $(INTERP_OBJ)
-	vsc -o $@ $^ $(SCMFLAGS) -Wc,-Llib
+	$(VSC) -o $@ $^ $(SCMFLAGS) -Wc,-Llib -Wc,-Lvendor/lib
 
 ifeq ($(ENABLE_WINDOWS),y)
 # I don't like this, any files vsc doesn't understand should just be passed to cc
@@ -244,8 +257,8 @@ lib/wasm/libvscheme.a : $(WASM_OBJ)
 	emar rcs $@ $^
 endif
 
-build/%.o : build/%.scm
-	$(PATCH) vsc -c $< -o $@ $(SCMFLAGS) -Wc,-fPIC -Iinclude -Ibuild/include
+build/%.o : build/%.scm $(VSC_DEP)
+	$(PATCH) $(VSC) -c $< -o $@ $(SCMFLAGS) -Wc,-fPIC -Iinclude -Ibuild/include
 build/%.o : build/%.c
 	$(CC) -c $< -o $@ $(CFLAGS) $(IFLAGS) -Iruntime -Isrc
 
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -54,12 +54,26 @@ feature_scmflags=""
 if [ "$windows" = "n" ]; then feature_scmflags+="-Ddisable-platform-windows "; fi
 if [ "$wasm" = "n" ]; then feature_scmflags+="-Ddisable-platform-emscripten "; fi
 
-if [ "$have_bison" = "n" ] && [ src/ffi.y -nt bootstrap/src/ffi.tab.c ]; then
-  echo "warning: bison not found and src/ffi.y is newer than bootstrap/src/ffi.tab.c;"
+# Is $1 (grammar source) newer than $2 (pre-generated output)?
+# Prefer git history over mtimes so fresh checkouts don't warn spuriously.
+is_stale() {
+  if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+    # uncommitted changes to the source mean the generated file can't be current
+    if ! git diff --quiet HEAD -- "$1" 2>/dev/null; then return 0; fi
+    src_time=$(git log -1 --format=%ct -- "$1")
+    gen_time=$(git log -1 --format=%ct -- "$2")
+    [ -n "$src_time" ] && [ -n "$gen_time" ] && [ "$src_time" -gt "$gen_time" ]
+  else
+    [ "$1" -nt "$2" ]
+  fi
+}
+
+if [ "$have_bison" = "n" ] && is_stale src/ffi.y bootstrap/src/ffi.tab.c; then
+  echo "warning: bison not found and src/ffi.y has changed since bootstrap/src/ffi.tab.c was generated;"
   echo "         the pre-generated parser may be stale"
 fi
-if [ "$have_lex" = "n" ] && [ src/ffi.l -nt bootstrap/src/ffi.lex.c ]; then
-  echo "warning: lex/flex not found and src/ffi.l is newer than bootstrap/src/ffi.lex.c;"
+if [ "$have_lex" = "n" ] && is_stale src/ffi.l bootstrap/src/ffi.lex.c; then
+  echo "warning: lex/flex not found and src/ffi.l has changed since bootstrap/src/ffi.lex.c was generated;"
   echo "         the pre-generated lexer may be stale"
 fi
 
